const express = require("express");
const router = express.Router();
const Case = require("../models/Case");
const LoginLog = require("../models/LoginLog");
const User = require("../models/User");

/* ================= CREATE CASE FROM LOGIN LOG ================= */
router.post("/create", async (req, res) => {
  try {
    const { logId, actionTaken, threatType, notes, severity } = req.body;

    // Find the login log
    const log = await LoginLog.findById(logId);
    if (!log) {
      return res.status(404).json({ message: "Login log not found" });
    }

    // Check if case already exists for this log
    const existingCase = await Case.findOne({ loginLogId: logId });
    if (existingCase) {
      return res.status(400).json({ 
        message: "Case already exists for this log",
        case: existingCase
      });
    }

    // Create new case
    const newCase = new Case({
      email: log.email,
      userId: log.userId,
      loginLogId: log._id,
      status: "Open",
      severity: severity || "Medium",
      actionTaken: actionTaken || "Investigation Pending",
      threatType: threatType || determineThreatType(log),
      notes: notes || generateNotes(log),
      ipAddress: log.ipAddress,
      deviceId: log.deviceId,
      country: log.country,
      riskScore: log.riskScore,
      riskLevel: log.riskLevel,
      loginTimestamp: log.createdAt
    });

    await newCase.save();

    // Update the login log to mark as reported
    log.isReported = true;
    log.resolved = false;
    await log.save();

    // Emit real-time alert
    const io = req.app.get("io");
    if (io) {
      io.to("role:admin").emit("case:created", {
        caseId: newCase._id,
        email: newCase.email,
        threatType: newCase.threatType,
        riskScore: newCase.riskScore
      });
    }

    res.status(201).json({
      success: true,
      message: "Case created successfully",
      case: newCase
    });

  } catch (error) {
    console.error("Case creation error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= AUTO-CREATE CASE FROM HIGH RISK LOGIN ================= */
router.post("/auto-create", async (req, res) => {
  try {
    const { logId } = req.body;

    const log = await LoginLog.findById(logId);
    if (!log) {
      return res.status(404).json({ message: "Login log not found" });
    }

    // Only auto-create for high risk
    if (log.riskScore < 60) {
      return res.status(400).json({ 
        message: "Risk score too low for automatic case creation" 
      });
    }

    const existingCase = await Case.findOne({ loginLogId: logId });
    if (existingCase) {
      return res.json({ 
        success: true, 
        message: "Case already exists",
        case: existingCase 
      });
    }

    const newCase = new Case({
      email: log.email,
      userId: log.userId,
      loginLogId: log._id,
      status: "Open",
      severity: log.riskScore >= 80 ? "Critical" : log.riskScore >= 60 ? "High" : "Medium",
      actionTaken: "Automatic Detection - Investigation Required",
      threatType: determineThreatType(log),
      notes: generateNotes(log),
      ipAddress: log.ipAddress,
      deviceId: log.deviceId,
      country: log.country,
      riskScore: log.riskScore,
      riskLevel: log.riskLevel,
      loginTimestamp: log.createdAt,
      autoGenerated: true
    });

    await newCase.save();

    log.isReported = true;
    await log.save();

    const io = req.app.get("io");
    if (io) {
      io.to("role:admin").emit("case:auto-created", {
        caseId: newCase._id,
        email: newCase.email,
        threatType: newCase.threatType,
        riskScore: newCase.riskScore
      });
    }

    res.status(201).json({
      success: true,
      message: "Case auto-created from high-risk login",
      case: newCase
    });

  } catch (error) {
    console.error("Auto case creation error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= GET ALL CASES ================= */
router.get("/", async (req, res) => {
  try {
    const { status, severity, email } = req.query;
    
    let query = {};
    if (status) query.status = status;
    if (severity) query.severity = severity;
    if (email) query.email = email;

    const cases = await Case.find(query)
      .sort({ createdAt: -1 })
      .limit(100);

    res.json(cases);
  } catch (error) {
    console.error("Fetch cases error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= GET SINGLE CASE ================= */
router.get("/:id", async (req, res) => {
  try {
    const caseData = await Case.findById(req.params.id);
    if (!caseData) {
      return res.status(404).json({ message: "Case not found" });
    }
    res.json(caseData);
  } catch (error) {
    console.error("Fetch case error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= UPDATE CASE ================= */
router.put("/:id", async (req, res) => {
  try {
    const { actionTaken, threatType, notes, status, severity, assignedTo } = req.body;

    const updatedCase = await Case.findByIdAndUpdate(
      req.params.id,
      {
        $set: {
          ...(actionTaken && { actionTaken }),
          ...(threatType && { threatType }),
          ...(notes && { notes }),
          ...(status && { status }),
          ...(severity && { severity }),
          ...(assignedTo && { assignedTo }),
          updatedAt: new Date()
        }
      },
      { new: true }
    );

    if (!updatedCase) {
      return res.status(404).json({ message: "Case not found" });
    }

    // If resolved, mark the related login log
    if (status === "Resolved") {
      await LoginLog.findByIdAndUpdate(updatedCase.loginLogId, {
        resolved: true
      });
    }

    res.json({
      success: true,
      message: "Case updated successfully",
      case: updatedCase
    });

  } catch (error) {
    console.error("Update case error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= DELETE CASE ================= */
router.delete("/:id", async (req, res) => {
  try {
    const deletedCase = await Case.findByIdAndDelete(req.params.id);
    if (!deletedCase) {
      return res.status(404).json({ message: "Case not found" });
    }

    // Unmark the login log
    if (deletedCase.loginLogId) {
      await LoginLog.findByIdAndUpdate(deletedCase.loginLogId, {
        isReported: false,
        resolved: false
      });
    }

    res.json({ success: true, message: "Case deleted" });
  } catch (error) {
    console.error("Delete case error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= GET CASE STATS ================= */
router.get("/stats/summary", async (req, res) => {
  try {
    const total = await Case.countDocuments();
    const open = await Case.countDocuments({ status: "Open" });
    const inProgress = await Case.countDocuments({ status: "In Progress" });
    const resolved = await Case.countDocuments({ status: "Resolved" });
    const critical = await Case.countDocuments({ severity: "Critical" });

    res.json({
      total,
      open,
      inProgress,
      resolved,
      critical
    });
  } catch (error) {
    console.error("Case stats error:", error);
    res.status(500).json({ message: "Server error" });
  }
});

/* ================= HELPER FUNCTIONS ================= */

/**
 * Determine threat type from login log data
 */
function determineThreatType(log) {
  const threats = [];

  if (log.keystrokeAnalysis?.anomalyScore > 40) {
    threats.push("Behavioral Anomaly");
  }
  if (log.travelAnalysis?.impossibleTravel) {
    threats.push("Impossible Travel");
  }
  if (log.riskScore >= 80) {
    threats.push("Account Takeover Attempt");
  }
  if (log.status === "blocked") {
    threats.push("Blocked Login");
  }
  if (log.riskComponents?.deviceRisk?.isNewDevice) {
    threats.push("New Device Login");
  }
  if (log.temporalAnalysis?.isUnusualTime) {
    threats.push("Unusual Login Time");
  }

  return threats.length > 0 ? threats.join(", ") : "Suspicious Activity";
}

/**
 * Generate notes from login log analysis
 */
function generateNotes(log) {
  const notes = [];

  notes.push(`Risk Score: ${log.riskScore}/100 (${log.riskLevel} Risk)`);
  notes.push(`IP: ${log.ipAddress}`);
  notes.push(`Location: ${log.state || 'Unknown'}, ${log.country || 'Unknown'}`);
  notes.push(`Device: ${log.device} (${log.browser} on ${log.os})`);

  if (log.keystrokeAnalysis?.anomalyScore > 40) {
    notes.push(`Behavioral Anomaly: ${log.keystrokeAnalysis.anomalyScore}% deviation`);
  }

  if (log.travelAnalysis?.impossibleTravel) {
    notes.push(`Impossible Travel: ${log.travelAnalysis.distanceTraveled}km in ${log.travelAnalysis.timeSinceLastLogin}h`);
  }

  if (log.threatExplanation?.reasons?.length > 0) {
    notes.push(`Reasons: ${log.threatExplanation.reasons.join('; ')}`);
  }

  return notes.join('\n');
}

module.exports = router;