const express = require("express");
const router = express.Router();

/**
 * HONEYPOT SYSTEM
 * Tracks attacker behavior when they access fake data
 */

// Track honeypot interactions
router.post("/interaction", async (req, res) => {
    try {
        const { action, details, timestamp } = req.body;
        const email = req.user?.email || 'unknown';
        
        console.log(`🪤 HONEYPOT: ${email} - ${action} - ${details}`);
        
        // Emit real-time alert to admin
        const io = req.app.get("io");
        if (io) {
            io.to("role:admin").emit("honeypot:interaction", {
                email,
                action,
                details,
                timestamp
            });
        }
        
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ message: "Error" });
    }
});

// Alert when attacker performs suspicious action
router.post("/alert", async (req, res) => {
    try {
        const { alertType, action, email } = req.body;
        
        console.log(`🚨 HONEYPOT ALERT: ${email} performed ${action}`);
        
        // Create a case automatically
        const Case = require("../models/Case");
        const User = require("../models/User");
        
        const user = await User.findOne({ email });
        
        if (user) {
            await Case.create({
                email: email,
                userId: user._id,
                status: "Open",
                severity: "Critical",
                actionTaken: "Honeypot Triggered - Attacker Detected",
                threatType: `Honeypot: ${action}`,
                notes: `Attacker interacted with fake data: ${action}. This confirms malicious intent.`,
                riskScore: 100,
                riskLevel: "Critical",
                autoGenerated: true
            });
            
            console.log(`🛡️ Case created for honeypot trigger: ${email}`);
        }
        
        // Emit critical alert
        const io = req.app.get("io");
        if (io) {
            io.to("role:admin").emit("honeypot:triggered", {
                email,
                action,
                alertType
            });
        }
        
        res.json({ success: true, message: "Alert logged" });
    } catch (error) {
        console.error("Honeypot alert error:", error);
        res.status(500).json({ message: "Error" });
    }
});

// Get honeypot stats
router.get("/stats", async (req, res) => {
    try {
        const Case = require("../models/Case");
        const honeypotCases = await Case.find({ threatType: /Honeypot/i }).countDocuments();
        
        res.json({
            honeypotTriggers: honeypotCases,
            activeSince: new Date().toISOString()
        });
    } catch (error) {
        res.status(500).json({ message: "Error" });
    }
});

module.exports = router;