const mongoose = require("mongoose");

const caseSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  loginLogId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "LoginLog"
  },
  status: {
    type: String,
    enum: ["Open", "In Progress", "Resolved", "Closed"],
    default: "Open"
  },
  severity: {
    type: String,
    enum: ["Low", "Medium", "High", "Critical"],
    default: "Medium"
  },
  actionTaken: {
    type: String,
    default: "Pending Investigation"
  },
  threatType: {
    type: String,
    default: "Unknown"
  },
  notes: {
    type: String,
    default: ""
  },
  ipAddress: String,
  deviceId: String,
  country: String,
  riskScore: Number,
  riskLevel: String,
  loginTimestamp: Date,
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  resolvedAt: Date,
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  }
}, { timestamps: true });

module.exports = mongoose.model("Case", caseSchema);